kind: Service
apiVersion: v1
metadata:
  name: redis-master
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  labels:
    app: redis
    role: master
spec:
  ports:
  - port: 6379
    targetPort: redis-server
  selector:
    app: redis
    role: master
